### ISSUE TITLE
string "item" in extent causes an import error

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/archivesspace-development#10]
` <extent type="computed" unit="items">1 item</extent>`
throws the error
`Error: #&lt;RuntimeError: Problem creating &#39;Abreu, Juan&#39;: Invalid value: item&gt;`
whereas 
` <extent type="computed" unit="items">1</extent>`
does not.

NB the same is not true for ` <extent type="computed" unit="folders">1 folder</extent>` and other values.

**Comment by jrgriffiniii** [comment]
This should be explored upstream, as this may be triggered by a core ArchivesSpace bug.

**Comment by regineheberlein** [comment]
apparently this has to do with our local config
