### ISSUE TITLE
EAD imports timeout for certain PULFA finding aid XML Documents

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/archivesspace-development#23]
MC001.04 timed out when attempting to import this into the local development environment

**Comment by jrgriffiniii** [comment]
I'm having trouble reproducing this without incurring the following:

![image](https://user-images.githubusercontent.com/1443986/84941641-a9a2b700-b0af-11ea-9aa9-d65df67a2e75.png)

**Comment by regineheberlein** [comment]
this may only affect our local test instance; closing for now
