### ISSUE TITLE
Normalized date tag appearing alongside title in Finding Aid Data

### ISSUE THREAD

**Issue by Will-Clements** [pulibrary/archivesspace-development#33]

**Comment by regineheberlein** [comment]
Need to de-nest date from titleproper

**Comment by regineheberlein** [comment]
Needs more analysis--it doesn't always happen, e.g. C0118 imports fine despite the nested date (ASpace correctly maps it to the date fields and strips it from the title)

**Comment by regineheberlein** [comment]
This happens because the Finding Aid Data area "title" field in ASpace expects a string but pulls from the mixed-content eadheader/filedesc/titleproper EAD field. Need to change the transformation to convert to string for import.
