### ISSUE TITLE
move all physloc/@text to the location record note field

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/archivesspace-development#71]
as discussed on Slack. excepting those mapped to container profiles

**Comment by regineheberlein** [comment]
@faithc Can you give context/details?

**Comment by regineheberlein** [comment]
this affects dsc[2]//physloc[@type="text"], dsc[1]//physloc

**Comment by regineheberlein** [comment]
add @type="note" to EAD

include textual physloc in top_containers, also with @type="note"

remove those from EAD

**Comment by regineheberlein** [comment]
dsc2 elements already have vetted content pertaining to container location; content of dsc1 elements also supports this:
[get-dsc1-physlocs.xlsx](https://github.com/pulibrary/archivesspace-development/files/5524087/get-dsc1-physlocs.xlsx)

**Comment by regineheberlein** [comment]
since container_location note is a property of the link between container and location, this will require assigning a location to non-entified dsc1 containers.

**Comment by regineheberlein** [comment]
this requires entification of the dsc1 containers, which in turn requires first knowing what the top containers in our classic container data are. 
[get-container-scenarios.txt](https://github.com/pulibrary/archivesspace-development/files/5537679/get-container-scenarios.txt)

**Comment by regineheberlein** [comment]
@Faithc on Slack: "In terms of the container scenarios you provided, it seems like in all cases the first container listed should be considered the top container; but curious what others think."

**Comment by regineheberlein** [comment]
@faithc so for the two scenarios box/case and case/box, you would say one is a case in a box, and one is a box in a case?

**Comment by faithc** [comment]
Without seeing the containers, that's what I would guess. Might be helpful to have component IDs to refer to?

**Comment by regineheberlein** [comment]
@faithc sure thing, here you go:

[get-container-scenarios-full.txt](https://github.com/pulibrary/archivesspace-development/files/5526520/get-container-scenarios-full.txt)

**Comment by faithc** [comment]
I don't even know what rcpxg is haha. Think whoever does might want to take a gander.

**Comment by regineheberlein** [comment]
It's Graphic Arts. Lmk.

**Comment by faithc** [comment]
Ah. Yeah, I'm not sure. I think this is probably a question for Julie.

**Comment by regineheberlein** [comment]
Ok, can you ask her please?

**Comment by faithc** [comment]
I'll get back to you.

**Comment by regineheberlein** [comment]
Just taking a stab here at saying the iffy ones are probably:
- box/case and case/box
- box/reel
- box/item
- portfolio/packet
- box/cassette
- box/tape
- box/volume
- box/binder

FYI the empty ones are dsc2 containers, so I would treat every other container in that component as a subcontainer.

**Comment by faithc** [comment]
Re: the two graphic arts collections, without access to the boxes and after asking several colleagues, it seems as if case is the top container for RCPXG-5830371.1, and box the top container for RCPXG-5830371.2. I could ask someone to confirm this by looking at one container from each collection if you think that's necessary.

**Comment by regineheberlein** [comment]
Thanks @faithc.

**Comment by regineheberlein** [comment]
need to exclude "primary run" containers in univarchives
